//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InrappAdminInterim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admDelregister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admDelregister()
        {
            this.admForvantadleverans = new HashSet<admForvantadleveran>();
            this.admUppgiftsskyldighets = new HashSet<admUppgiftsskyldighet>();
        }
    
        public int delregisterid { get; set; }
        public int registerid { get; set; }
        public string delregisternamn { get; set; }
        public string beskrivning { get; set; }
        public string kortnamn { get; set; }
        public bool inrapporteringsportal { get; set; }
        public string slussmapp { get; set; }
        public System.DateTime skapaddatum { get; set; }
        public string skapadav { get; set; }
        public System.DateTime andraddatum { get; set; }
        public string andradav { get; set; }
    
        public virtual admRegister admRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admForvantadleveran> admForvantadleverans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admUppgiftsskyldighet> admUppgiftsskyldighets { get; set; }
    }
}
