//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InrappAdminInterim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admForvantadleveran
    {
        public int forvantadleveransid { get; set; }
        public int delregisterid { get; set; }
        public int filkravid { get; set; }
        public string period { get; set; }
        public System.DateTime uppgiftsstart { get; set; }
        public System.DateTime uppgiftsslut { get; set; }
        public System.DateTime rapporteringsstart { get; set; }
        public System.DateTime rapporteringsslut { get; set; }
        public System.DateTime rapporteringsenast { get; set; }
        public Nullable<System.DateTime> paminnelse1 { get; set; }
        public Nullable<System.DateTime> paminnelse2 { get; set; }
        public Nullable<System.DateTime> paminnelse3 { get; set; }
        public System.DateTime skapaddatum { get; set; }
        public string skapadav { get; set; }
        public System.DateTime andraddatum { get; set; }
        public string andradav { get; set; }
    
        public virtual admDelregister admDelregister { get; set; }
    }
}
