//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InrappAdminInterim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB11Entities : DbContext
    {
        public DB11Entities()
            : base("name=DB11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admDelregister> admDelregisters { get; set; }
        public virtual DbSet<admFAQ> admFAQs { get; set; }
        public virtual DbSet<admFAQKategori> admFAQKategoris { get; set; }
        public virtual DbSet<admForvantadfil> admForvantadfils { get; set; }
        public virtual DbSet<admForvantadleveran> admForvantadleverans { get; set; }
        public virtual DbSet<admInformation> admInformations { get; set; }
        public virtual DbSet<admKonfiguration> admKonfigurations { get; set; }
        public virtual DbSet<admRegister> admRegisters { get; set; }
        public virtual DbSet<admUppgiftsskyldighet> admUppgiftsskyldighets { get; set; }
        public virtual DbSet<Kontaktperson> Kontaktpersons { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<Organisationsenhet> Organisationsenhets { get; set; }
    }
}
