//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InrappAdminInterim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organisation()
        {
            this.admUppgiftsskyldighets = new HashSet<admUppgiftsskyldighet>();
            this.Kontaktpersons = new HashSet<Kontaktperson>();
            this.Organisationsenhets = new HashSet<Organisationsenhet>();
        }
    
        public int organisationsid { get; set; }
        public string landstingskod { get; set; }
        public string kommunkod { get; set; }
        public string inrapporteringskod { get; set; }
        public string organisationstyp { get; set; }
        public Nullable<int> lanid { get; set; }
        public string organisationsnr { get; set; }
        public string organisationsnamn { get; set; }
        public string hemsida { get; set; }
        public string epostadress { get; set; }
        public string telefonnr { get; set; }
        public string adress { get; set; }
        public string postnr { get; set; }
        public string postort { get; set; }
        public string epostdoman { get; set; }
        public System.DateTime aktivfrom { get; set; }
        public Nullable<System.DateTime> aktivtom { get; set; }
        public System.DateTime skapaddatum { get; set; }
        public string skapadav { get; set; }
        public System.DateTime andraddatum { get; set; }
        public string andradav { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admUppgiftsskyldighet> admUppgiftsskyldighets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontaktperson> Kontaktpersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organisationsenhet> Organisationsenhets { get; set; }
    }
}
